# This YAML file defines a Secret in Kubernetes.
# The Secret is named "mysql-ingress-tls-secret" and belongs to the "database" namespace.
#
# The Secret stores TLS certificate and private key data for securing ingress traffic.

apiVersion: v1
kind: Secret
metadata:
  name: mysql-ingress-tls-secret
  namespace: database
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURORENDQWh5Z0F3SUJBZ0lVVmlwQUpVRlZuM1VXV25PMi96RDVyKytsdzNNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0d6RVpNQmNHQTFVRUF3d1FiWGx6Y1d3dWJXRnlkbVZzTG1OdmJUQWVGdzB5TlRBeE1UQXhNekE1TWpOYQpGdzB6TXpBek1qa3hNekE1TWpOYU1Cc3hHVEFYQmdOVkJBTU1FRzE1YzNGc0xtMWhjblpsYkM1amIyMHdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHJqdlFwQ0xlR2d3eUxkOFowUFBWY1Rhc1UKdzR0VlFUZkc5SFpGd0RGWXUzb1p2aythRFRSU24xRVgyTXBBbUdJL0IzRmlKNVRjSVZidDRGMXFhSkhpL2tkWAo5U1BXaEN0aVRSaUw3Z1kvZ1NaSGFmalB4WGViVkRNWjFjb3FCbjJHS2VuNmZxdGY1RnJRcmhkQWJsTTArWXJYCm4wdnZOcFdYUno3WU9Wd1N0OGdYQ253NmNyMmpwWU1zQUJmVmhha3NnVTl5SEZlWWJ6SXc3a1dTdDhWUWxWNFMKR3RFeGFxcGFiUTh6KzJqQ3VEMlRBUzJud3UxbGVxYWRrdGlTOGgrREtuby9SSC9vVlJqQlpRdGJBUXhpV0RSSgpZQWUxdzRzY0N0aFcyakVMZlNLZHFSbUlST2JrOUZweFQ1VFVjMXozWTRKOXY1Rkk4aDhGL0xES2c3bXpBZ01CCkFBR2pjREJ1TUIwR0ExVWREZ1FXQkJTTHVYRlA4Qi82am9QaEhyYk4wSXF4ekNYRkNqQWZCZ05WSFNNRUdEQVcKZ0JTTHVYRlA4Qi82am9QaEhyYk4wSXF4ekNYRkNqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01Cc0dBMVVkRVFRVQpNQktDRUcxNWMzRnNMbTFoY25abGJDNWpiMjB3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUlXSXV2MWtqS1hECkJRVjM2Vmp1Wnlad0NaMFU3NFNRREg1c2pFcW1NWWQreHhPenFiRmthK2hFdGxmK3BXbTUrSzFYN213NGNWSjkKWmR4UEgxR1dCQTNJU0JwMmRNay9TRXh5Z3lSN3R4czI5Tll0cHREK2JTK1FjQVhmdHoyZjFKYi9tbHd4dHorcQpnOTRnREwzMGl5dW5IMEYvQmxaa2NyS0ZSbEQzR1U5amErU3J5V2phSklZVnlTRkpKWVc0VGlIcUpCeGllL1M4CnJCdVdHeGtqcDZOTWpxeUVHZFVEOThqR0tRVjd6T2lQMy9DdUlkRG5yZEFxRE4rRldRUTd6T20rV0ZYMDdVL20KSjR1VkZhdnNlU2hRNXNOVUM1bW9xWTFVMGVLYUZWQ1hqTit3RjZIczYvNjl0NkdMMDRDMjA3U1p5clJZMjYrNQo5aDdPSVQzOWRqST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRHJqdlFwQ0xlR2d3eUwKZDhaMFBQVmNUYXNVdzR0VlFUZkc5SFpGd0RGWXUzb1p2aythRFRSU24xRVgyTXBBbUdJL0IzRmlKNVRjSVZidAo0RjFxYUpIaS9rZFg5U1BXaEN0aVRSaUw3Z1kvZ1NaSGFmalB4WGViVkRNWjFjb3FCbjJHS2VuNmZxdGY1RnJRCnJoZEFibE0wK1lyWG4wdnZOcFdYUno3WU9Wd1N0OGdYQ253NmNyMmpwWU1zQUJmVmhha3NnVTl5SEZlWWJ6SXcKN2tXU3Q4VlFsVjRTR3RFeGFxcGFiUTh6KzJqQ3VEMlRBUzJud3UxbGVxYWRrdGlTOGgrREtuby9SSC9vVlJqQgpaUXRiQVF4aVdEUkpZQWUxdzRzY0N0aFcyakVMZlNLZHFSbUlST2JrOUZweFQ1VFVjMXozWTRKOXY1Rkk4aDhGCi9MREtnN216QWdNQkFBRUNnZ0VBRi9uRWF6cktaMFFHYmxtaUZ1bXZkWllvTUNSWkZiUGVKLzl3M0ZlY0RqS0MKMG9UMjJEQzQzeUg5SUlhOXkwWlhWWi85eitaRWRnVmtzakNRZ1lpa05LejUrUDlvQnVrTCsyVHFkeStpYml0SQppS05HSW11d2FWeHdHUlNVRDZQNmVjSGhZVkFzUkVYYlluc2R2YjZjOUhyandWK2kzSFc3VXhyNjBBcENqMXI0Cll0OFR0NngxNXcvR0JWNm92SFdHQ2ZJZ01FMlc3Vjl3dFpwanZrODFSanRXSk95ejgyN2pmNHRtVnVSbEo0QzEKOFNJa0RZUGxOWHlIWStRK09TSzFSalNYakFoSUhFY1o4Y3JwT250TUJJTHRvYzJ1ZTZNeXRNaU1QdmIyOHhDUQpqNHZRUVEvV3A0QitPaXZHMFdqWEwrMTNobFZSc1MwSEZ5WGhrc2VQZlFLQmdRRDJRZTBXNUJsS2lvSk40Yi9vCldRUVBsQlBYaHNGd084QW1LaTE0cDlRRVI1UkRHbjNQdXNTbUl5ai8yZUJ1WFZnSHVqaFRraFhNdWc1Z2Z6elEKNFA0dTVHMDBkQ24wY0h0bFYweDRKV2hhQmV3bll0aGxNam9GMzZZQm0xV3pwMDJMc1N2dXRIdzN5K05OMUpPcwpzL1VMMys1L3JxVGgvUStza3lNeVJFNGNCUUtCZ1FEMDRLc0J5MlV3dVFOandwMi9NQi9MUFFzZXJKaXozRHpvCmFQVmRiQWlFVXRiV09PdFNGeHpnSktnTzRWY1lhVlY4WDB2S1RpdXJsVVVPYjJlQnZkcEpxUUsxTXlJM0ErY00KUG9YOVhlbFpGUVdpSkxXUDdUa2JBYXA1ZEZacm53bTBxWlR6T1BIUkcxMFdHcjl3SEtzeUwrWGM5UE5zVTc1YwprUVFIRmdHa1Z3S0JnUURxUW56UU1kejlWQlh4RUxnR3grZGRDbmgxcHZPTldNbkpoSVlOS1ZvL1YvaHFmV0VCCm82SStpV1FQUDZ5SVVMUFZaZ2ovTnhFVjJFaWs4MlZmTHltZVloNmdyNERaejhjUytLRCtDbGZpaTQvRFIveWoKQjh5Nm1hN0tDSUxXakdqd1luSndlYkZSUXR2UXhsQlZFandpTjd3aUtua2ZvaVN1L3FtVXYvV3VJUUtCZ0VmNwp0eWs2NGc4VmcrS1NkZzZhbGU0SGpycEFvRTdXNGV5cjFkelZnaGRyeG8ySWc5eEl3UXMrbTB4c2YwN0V3QVZrCmVnSUpRcHNZc1FrU1JJb0dCaUg3RmJtd1ExR0t5eU4xU2F2MkxEOHNoOUJuSEJ3bjdzNTZpZU5VQ0lkd1k4a0EKeExGT3Z2N3FIVTMvSk9GTy9DQXZwbEZ5akEvKytnbDU4NFlsdU92WEFvR0FTRUUrVjIxS0IxV2pkWXhuWFRlSgpnUmZWUWFNRjR5alA4TmFkTTFaRkdkQmNRTHJZTGVOTlBVeml3eVkzU0lkWWR1UWIyL01MYXRsOS9JZ0tWTmw4CkQ0RVRNWWNMeElzeGY3enp0Z3RYZzlWZllST0tITW1oQ0cyRFNnSG1OQ2JUVERHZ3ZpdElTRmFBdTUxRC9rakkKaE5JUXp2cHZjazk0UmdOYVcwMUY4TzA9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

---

# This YAML file defines an Ingress resource in Kubernetes.
# The Ingress is named "phpmyadmin-ingress" and belongs to the "database" namespace.
#
# The Ingress resource manages external access to the services within the cluster.
# It provides HTTP and HTTPS routing to the services.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  namespace: database
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # The annotation used by NGINX Ingress Controller to rewrite the target URL.
spec:
  tls:
  - hosts:
      - mysql.marvel.com  # The hostname for which the TLS certificate is valid.
    secretName: mysql-ingress-tls-secret  # The secret that contains the TLS certificate and key.
  rules:
  - host: mysql.marvel.com  # The hostname for which the rule applies.
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phpmyadmin-svc  # The service to which traffic should be directed.
            port:
              number: 80  # The port on the service to which traffic should be directed.
